"""add created_at updated_at column

Revision ID: 0003
Revises: 0002
Create Date: 2025-09-22 15:43:13.717598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        'tasks',
        'status',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'),
        existing_nullable=False,
        postgresql_using='status::taskstatus'
    )
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column(
        'users',
        'role',
        existing_type=sa.VARCHAR(),
        type_=sa.Enum('manager', 'worker', name='userrole'),
        existing_nullable=False,
        postgresql_using='role::userrole'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('manager', 'worker', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.alter_column('tasks', 'status',
               existing_type=sa.Enum('pending', 'in_progress', 'completed', name='taskstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'created_at')
    # ### end Alembic commands ###
